/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CarroFuzzy;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author Osmar
 */
public class Sensores extends javax.swing.JFrame {

    /**
     * Creates new form Sensores
     */
    public Sensores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rbAmarelo = new javax.swing.JRadioButton();
        rbVermelho = new javax.swing.JRadioButton();
        sliderVelocidade = new javax.swing.JSlider();
        sliderFarol = new javax.swing.JSlider();
        sliderCarro = new javax.swing.JSlider();
        rbEsquerdaObstruida = new javax.swing.JRadioButton();
        rbEsquerdaLivre = new javax.swing.JRadioButton();
        rbDireitaObstruida = new javax.swing.JRadioButton();
        rbDireitaLivre = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        rbVerde = new javax.swing.JRadioButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Entrada dos Sensores do Carro");

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("Velocidade");

        jLabel3.setText("Distância do Farol");

        jLabel4.setText("Distância do Carro da frente");

        jLabel5.setText("Farol");

        jLabel6.setText("Lateral Esquerda");

        jLabel7.setText("Lateral Direita");

        buttonGroup1.add(rbAmarelo);
        rbAmarelo.setText("Amarelo");
        rbAmarelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAmareloActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVermelho);
        rbVermelho.setText("Vermelho");

        sliderVelocidade.setMajorTickSpacing(10);
        sliderVelocidade.setMaximum(120);
        sliderVelocidade.setMinorTickSpacing(10);
        sliderVelocidade.setPaintLabels(true);
        sliderVelocidade.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        sliderFarol.setMajorTickSpacing(10);
        sliderFarol.setMinorTickSpacing(10);
        sliderFarol.setPaintLabels(true);

        sliderCarro.setMajorTickSpacing(10);
        sliderCarro.setMinorTickSpacing(10);
        sliderCarro.setPaintLabels(true);

        buttonGroup2.add(rbEsquerdaObstruida);
        rbEsquerdaObstruida.setText("Obstruída");

        buttonGroup2.add(rbEsquerdaLivre);
        rbEsquerdaLivre.setText("Livre");

        buttonGroup3.add(rbDireitaObstruida);
        rbDireitaObstruida.setText("Obstruída");

        buttonGroup3.add(rbDireitaLivre);
        rbDireitaLivre.setText("Livre");

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbVerde);
        rbVerde.setText("Verde");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addGap(176, 176, 176))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbDireitaLivre)
                        .addGap(18, 18, 18)
                        .addComponent(rbDireitaObstruida))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbVerde)
                        .addGap(18, 18, 18)
                        .addComponent(rbAmarelo)
                        .addGap(18, 18, 18)
                        .addComponent(rbVermelho))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rbEsquerdaLivre)
                        .addGap(18, 18, 18)
                        .addComponent(rbEsquerdaObstruida))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(sliderVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(sliderFarol, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sliderCarro, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(sliderVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel2)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sliderFarol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(sliderCarro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel4)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(rbVermelho)
                    .addComponent(rbAmarelo)
                    .addComponent(rbVerde))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbEsquerdaObstruida)
                    .addComponent(rbEsquerdaLivre))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(rbDireitaObstruida)
                    .addComponent(rbDireitaLivre))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnCalcular)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(83, 83, 83))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbAmareloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAmareloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbAmareloActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        //Instanciando as variáveis
        Acelerar acelerar = new Acelerar();
        double acelerar_saida;

        Freiar freiar = new Freiar();
        double freiar_saida;

        VirarEsquerda esquerda = new VirarEsquerda();
        double esquerda_saida;

        VirarDireita direita = new VirarDireita();
        double direita_saida;
        
        rbVerde.setActionCommand("0");
        rbAmarelo.setActionCommand("1");
        rbVermelho.setActionCommand("2");
        rbDireitaLivre.setActionCommand("true");
        rbDireitaObstruida.setActionCommand("false");
        rbEsquerdaLivre.setActionCommand("true");
        rbEsquerdaObstruida.setActionCommand("false");
        int farol = Integer.parseInt(buttonGroup1.getSelection().getActionCommand());
        String pistaDireita = buttonGroup3.getSelection().getActionCommand();
        String pistaEsquerda = buttonGroup2.getSelection().getActionCommand();
        int velocidade = sliderVelocidade.getValue();
        int distancia = sliderFarol.getValue();
        int distancia_carro = sliderCarro.getValue();
        int escolha;
        double direcao = 0.0;
        boolean sentido;
        String saida = "";
        boolean l_esquerda;
        boolean l_direita;

        //Passando para boolean os valores vindos sobre as pistas laterais
        if (pistaDireita.equals("true")) {
            l_direita = true;
        } else {
            l_direita = false;
        }
        if (pistaEsquerda.equals("true")) {
            l_esquerda = true;
        } else {
            l_esquerda = false;
        }

        //Verifica as entradas para chamar os métodos da lógica fuzzy
        if (farol == 0) {
            
            //Chama o método para acelerar
            saida += "Farol Verde!\n";
            acelerar_saida = acelerar.verificarAceleracao(farol, distancia, velocidade);

            //Verifica se o carro da frente está muito perto
            if (distancia_carro < 50 && (l_esquerda == true || l_direita == true)) {
                
                //Chama os métodos para as pistas esquerda e direita
                esquerda_saida = esquerda.pistaEsquerda(distancia_carro, velocidade, l_esquerda);
                direita_saida = direita.pistaDireita(distancia_carro, velocidade, l_direita);
                
                //Verifica qual retornou a maior saída
                if (esquerda_saida > direita_saida) {
                    direcao = esquerda_saida;
                    sentido = true;
                    saida += "Trocar de Pista! \nVirar Esquerda \n";
                } else if (direita_saida > esquerda_saida) {
                    direcao = direita_saida;
                    sentido = false;
                    saida += "Trocar de Pista! \nVirar Direita \n";
                } else if(l_direita == true && l_esquerda == true) {
                    Random random = new Random();
                    escolha = random.nextInt(10);
                    if (escolha < 5) {
                        direcao = direita_saida;
                        sentido = false;
                        saida += "Trocar de Pista! \nVirar Direita \n";
                    } else {
                        direcao = esquerda_saida;
                        sentido = true;
                        saida += "Trocar de Pista! \nVirar Esquerda \n";
                    }
                } else {
                    saida += "Não trocar de Pista! \n";
                }
            }
            String resultado = String.format("%.2f", acelerar_saida);
            saida += "Acelerar: " + resultado + "km/h \n";
        } else if (farol == 1) {
            //Chama os métodos para acelerar e frear
            saida += "Farol Amarelo!";
            acelerar_saida = acelerar.verificarAceleracao(farol, distancia, velocidade);
            freiar_saida = freiar.freiarCarro(farol, distancia, velocidade);
            
            //Verifica a distância e a velocidade para escolher a saída dos métodos
            if (velocidade > 60 && distancia < 50) {
                String resultado = String.format("%.2f", acelerar_saida);
                saida += "Acelerar: " + resultado + "km/h \n";
            } else if (velocidade <= 60 && distancia >= 50) {
                String resultado = String.format("%.2f", freiar_saida);
                saida += "Freiar: " + resultado + "km/h \n";
            } else {
                //Verifica qual das saídas tem o maior valor
                if (acelerar_saida > freiar_saida) {
                    String resultado = String.format("%.2f", acelerar_saida);
                    saida += "Acelerar: " + resultado + "km/h \n";
                } else {
                    String resultado = String.format("%.2f", freiar_saida);
                    saida += "Freiar: " + resultado + "km/h \n";
                }
            }
        } else {
            //Chama o método para frear
            saida += "Farol Vermelho!\n";
            freiar_saida = freiar.freiarCarro(farol, distancia, velocidade);
            String resultado = String.format("%.2f", freiar_saida);
            saida += "Frear: " + resultado + "km/h \n";
        }
        //Mostra a saída do sistema
        JOptionPane.showMessageDialog(null, saida, "Saída do Sistema", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sensores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sensores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sensores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sensores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sensores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbAmarelo;
    private javax.swing.JRadioButton rbDireitaLivre;
    private javax.swing.JRadioButton rbDireitaObstruida;
    private javax.swing.JRadioButton rbEsquerdaLivre;
    private javax.swing.JRadioButton rbEsquerdaObstruida;
    private javax.swing.JRadioButton rbVerde;
    private javax.swing.JRadioButton rbVermelho;
    private javax.swing.JSlider sliderCarro;
    private javax.swing.JSlider sliderFarol;
    private javax.swing.JSlider sliderVelocidade;
    // End of variables declaration//GEN-END:variables
}
